import { LifeValue } from "@shared/schema";

export const DEFAULT_VALUES: LifeValue[] = [
  { id: "1", name: "Rodzina", description: "Miłość i wsparcie najbliższych", position: null },
  { id: "2", name: "Zdrowie", description: "Dbanie o kondycję fizyczną i psychiczną", position: null },
  { id: "3", name: "Rozwój osobisty", description: "Ciągłe uczenie się i doskonalenie", position: null },
  { id: "4", name: "Praca zawodowa", description: "Kariera i realizacja zawodowa", position: null },
  { id: "5", name: "Przyjaźnie", description: "Budowanie trwałych relacji", position: null },
  { id: "6", name: "Uczciwość", description: "Prawdomówność i integralność", position: null },
  { id: "7", name: "Kreatywność", description: "Twórczość i innowacyjność", position: null },
  { id: "8", name: "Bezpieczeństwo finansowe", description: "Stabilność ekonomiczna", position: null },
  { id: "9", name: "Przygoda", description: "Poszukiwanie nowych doświadczeń", position: null },
  { id: "10", name: "Duchowość", description: "Rozwój wewnętrzny i transcendencja", position: null },
  { id: "11", name: "Niezależność", description: "Autonomia i wolność wyboru", position: null },
  { id: "12", name: "Wspólnota", description: "Przynależność do grupy", position: null },
  { id: "13", name: "Wiedza", description: "Zdobywanie i dzielenie się wiedzą", position: null },
  { id: "14", name: "Sprawiedliwość", description: "Równość i fair play", position: null },
  { id: "15", name: "Piękno", description: "Estetyka i harmonia", position: null },
  { id: "16", name: "Tradycja", description: "Szanowanie dziedzictwa kulturowego", position: null },
  { id: "17", name: "Innowacja", description: "Wprowadzanie zmian i nowości", position: null },
  { id: "18", name: "Odpowiedzialność", description: "Zobowiązanie i wiarygodność", position: null },
  { id: "19", name: "Współczucie", description: "Empatia i troska o innych", position: null },
  { id: "20", name: "Wolność", description: "Możliwość swobodnego działania", position: null },
  { id: "21", name: "Stabilność", description: "Przewidywalność i bezpieczeństwo", position: null },
  { id: "22", name: "Pasja", description: "Entuzjazm i zaangażowanie", position: null },
  { id: "23", name: "Prostota", description: "Minimalizm i klarowność", position: null },
  { id: "24", name: "Władza", description: "Wpływ i kontrola", position: null },
  { id: "25", name: "Popularność", description: "Uznanie społeczne", position: null },
  { id: "26", name: "Spokój", description: "Wewnętrzny harmonii i cisza", position: null },
  { id: "27", name: "Wyzwania", description: "Pokonywanie trudności", position: null },
  { id: "28", name: "Humor", description: "Radość i żartobliwość", position: null },
  { id: "29", name: "Elegancja", description: "Wyrafinowanie i styl", position: null },
  { id: "30", name: "Autentyczność", description: "Bycie sobą", position: null },
  { id: "31", name: "Cierpliwość", description: "Spokojne oczekiwanie", position: null },
  { id: "32", name: "Determinacja", description: "Wytrwałość w dążeniu do celu", position: null },
  { id: "33", name: "Optymizm", description: "Pozytywne nastawienie", position: null },
  { id: "34", name: "Dyscyplina", description: "Samokontrola i systematyczność", position: null },
  { id: "35", name: "Spontaniczność", description: "Naturalność i impulsywność", position: null },
  { id: "36", name: "Lojalność", description: "Wierność i oddanie", position: null },
  { id: "37", name: "Tolerancja", description: "Akceptacja różnorodności", position: null },
  { id: "38", name: "Odwaga", description: "Brak strachu przed wyzwaniami", position: null },
  { id: "39", name: "Mądrość", description: "Głębokie zrozumienie życia", position: null },
  { id: "40", name: "Miłość", description: "Głębokie uczucie i przywiązanie", position: null },
];
